var OVERWORLD = [
    [
        "wwDDDDDDDDDDDDDDDDDB",
        "GDDDDwDDDDDDDDDDDDDB",
        "RDDDwwDDDDDDDDDDDDDB",
        "GGRGwDDDDDDDDDDDDDDB",
        "FGGwwDDwDDDDDDDDDDDB",
        "GRFwwwwwDDDDDDDDDDDB",
        "RGGwwwwwwwDDwDDDDDDB",
        "GRGDDwwwwwwwwDDDDDDB",
        "RRGR DDwwwwwwSSSDDDB",
        "RGFGRDwwwDwwwwsSSDDB",
        "GGGGGwwDDDwwwwssSSDB",
        "GRGGGwwDBBwwwwwssSDD",
        "GRGRGwwwBBwwwwwwwsSD",
        "GGGGwwwwwwwwwwwwwww0",
        "FGRGwwwwwwwwwwwwwww0",
        "GRGGwDwwwwwwwwwwwww0",
        "GFGwwwwwwwwwwwwwwwwD",
        "RRGwwwwwwwwwwwwwwwDD",
        "RGGDDwwwBBDDwwwwwDDD",
        "GFGGDwwwwBDDwwwwDGDD"
    ],
    [
        "..DDDDDDDDDDDDDDDDDB",
        " RDDDDDDDDDDDDDDDDDB",
        " gRG..DDDDDDDDDDDDDB",
        "    .DDDDDDDDDDDDDDB",
        "   ..GD.GDDDDDDDDDDB",
        "   .....DDDDDDDDDDDB",
        "   .......DD.DDDDDDB",
        "   gg........gGDDDDB",
        "    rGG..D... ssgDDB",
        "     g..DD....  sGDB",
        "     ..DDD....   sDB",
        "     ..DBB.....   gD",
        "     ...BB.......  D",
        "    ...............W",
        "    ...............W",
        "    .g.............W",
        "   ................D",
        "   ...............DD",
        "   gg...BBDD.....DDD",
        "    g....BDGD...DDDD"
    ],
    [
        "..gRDDDDDDDDwwwDDDDB",
        "  rGRDDDDDDDwwwwDDDB",
        "    ..DDDDDDDwwwwDDB",
        "    .gDDDDDDDDwwDDDB",
        "   .. G.DDDDDDDDDDDB",
        "   .....DDDDDDDDDDDB",
        "   .....DDDD.GDDDDDB",
        "     ....DDD.  GDDDB",
        "       .DDD..    gGB",
        "      ..DD....    gB",
        "     ..GDD....    gB",
        "     ..gBB.....    D",
        "     ...BB.......  G",
        "    ....BB.........W",
        "    ...............W",
        "    . .............W",
        "   ................D",
        "   .....BB........DD",
        "     ...BBDD.....DDD",
        "     ...BBDDDDDDDDGD"
    ],
    [
        "..  gGRRGGGG...GGGGB",
        "     rrRRFRG....FGGB",
        "    ..grRGGRG....GGB",
        "    . ggRRGGGG..GFGB",
        "   ..  .RGGGFGGGGGGB",
        "   .....gRGRGGGFGGGB",
        "   .....rgGG. ggggGB",
        "     ...rrgg.   gggB",
        "       .grg..      B",
        "      ..rg....     B",
        "     .. rr....     B",
        "     .. bb.....    D",
        "     ...bb.......  D",
        "    ....bb.........W",
        "    ....bb.........W",
        "    . ..bb.........W",
        "   .....bb.........D",
        "   .....bb........DD",
        "     ...bbrG.....DDD",
        "     ...bbgrrgrGRRDD"
    ],
    [
        "..          ...    B",
        "            ....   B",
        "    ..       ....  B",
        "    .         ..   B",
        "   ..  .           B",
        "   .....           B",
        "   .....    .      B",
        "     ...    .      B",
        "       .   ..      B",
        "      ..  ....     B",
        "     ..   ....     B",
        "     ..   .....    D",
        "     ...  .......  G",
        "    ....  .........1",
        "    ....  .........1",
        "    . ..  .........1",
        "   .....  .........G",
        "   .....  ........gG",
        "     ...    .....grg",
        "     ...          gr"
    ],
    [
        "..          ...    B",
        "            ....   b",
        "    ..       ....  b",
        "    .         ..   B",
        "   ..  .           b",
        "   .....           b",
        "   .....    .      b",
        "     ...    .      B",
        "       .   ..      b",
        "      ..  ....     b",
        "     ..   ....     B",
        "     ..   .....    g",
        "     ...  .......   ",
        "    ....  ..........",
        "    ....  ..........",
        "    . ..  ..........",
        "   .....  ......... ",
        "   .....  ........  ",
        "     ...    .....   ",
        "     ...            "
    ],
    [
        "..          ...     ",
        "            ....    ",
        "    ..       ....   ",
        "    .         ..    ",
        "   ..  .            ",
        "   .....            ",
        "   .....    .       ",
        "     ...    .       ",
        "       .   ..       ",
        "      ..  ....      ",
        "     ..   ....      ",
        "     ..   .....     ",
        "     ...  .......   ",
        "    ....  ..........",
        "    ....  ..........",
        "    . ..  ..........",
        "   .....  ......... ",
        "   .....  ........  ",
        "     ...    .....   ",
        "     ...            "
    ]
];

var TEST = [
    [
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG",
        "GGGGGGGGGG"
    ],
    [
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          "
    ],
    [
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          ",
        "          "
    ]
];